### ISSUE TITLE
Update to .Net 7

### ISSUE THREAD

**Issue by DanielBaumert** [exomia/vulkan-api#53]
- [ ] ~~[ UTF-8 string literals](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#utf-8-string-literals)~~
- [x] [LibraryImportAttribute](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-7#pinvoke-source-generation)

**Comment by baetz-daniel** [comment]
done?

**Comment by baetz-daniel** [comment]
Samples to get the pointer from a readonly span<bytes> (scoped):

```c#
var rs = "my app"u8;
byte p = rs.GetPinnableReference();  
byte* ptr = &p;
```

```c#
var rs = "my app"u8;
byte* ptr = (byte*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(rs))
```

**Remarks:** 
Unsafe code! If you do not know what this code will do; do not use it! (as it might have some side effects with incorrect usage!)


```c#
int   maxByteCount = Encoding.UTF8.GetMaxByteCount(str.Length)        + sizeof(int) + 1;
byte* ptr          = (byte*)NativeMemory.Alloc((nuint)(maxByteCount)) + sizeof(int);
GC.AddMemoryPressure(*(int*)(ptr - sizeof(int)) = maxByteCount);

fixed (char* srcPointer = str)
{
    *(ptr + Encoding.UTF8.GetBytes(srcPointer, str.Length, ptr, maxByteCount)) = 0;
}
// use 'ptr', store it or free it
```

**Remarks:** 
This pointer is allocated on the heap and will stay valid until released/freed!
This code will allocate 4 bytes more than needed to store the length of the string.
And will also inform the GC about the allocated memory.

```c#
int maxByteCount = *(int*)(ptr - sizeof(int));
NativeMemory.Free((ptr - sizeof(int)));
GC.RemoveMemoryPressure(maxByteCount);
```
